extent.reporter.spark.start=true
extent.reporter.spark.out=target/ExtentReport/ExtentSpark.html
 
extent.reporter.html.start=false
extent.reporter.log.start=false
 
# optional project info
system.info.os=Windows
system.info.browser=Chrome